language: python
python:
  - "3.4"
cache: pip3
before_install:
  - sudo apt-get install -y  gradle maven openjdk-8-jdk
  - sudo apt-get install -y python3-dev python3-pip python3-setuptools

install:
  - pip3 install -r requirements.txt

script:
  - python3 ./tests/test_run_time.py
