-- MySQL Script generated by MySQL Workbench
-- Mon 27 Aug 2018 01:03:54 PM MDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Merge_Data
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Merge_Data` ;

-- -----------------------------------------------------
-- Schema Merge_Data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Merge_Data` DEFAULT CHARACTER SET utf8 ;
USE `Merge_Data` ;

-- -----------------------------------------------------
-- Table `Merge_Data`.`Repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Repository` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Repository` (
  `id` INT NOT NULL,
  `update_date` DATETIME NULL,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(400) NULL,
  `language` VARCHAR(20) NULL,
  `watch_num` INT NULL,
  `star_num` INT NULL,
  `fork_num` INT NULL,
  `issue_num` INT NULL,
  `size` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Merge_Scenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Merge_Scenario` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Merge_Scenario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `merge_commit_hash` CHAR(40) NULL,
  `ancestor_commit_hash` CHAR(40) NULL,
  `parent1_commit_hash` CHAR(40) NULL,
  `parent2_commit_hash` CHAR(40) NULL,
  `parallel_changed_file_num` INT NULL,
  `merge_commit_can_compile` INT NULL,
  `merge_commit_can_pass_test` INT NULL,
  `ancestor_can_compile` INT NULL,
  `ancestor_can_pass_test` INT NULL,
  `parent1_can_compile` INT NULL,
  `parent1_can_pass_test` INT NULL,
  `parent2_can_compile` INT NULL,
  `parent2_can_pass_test` INT NULL,
  `merge_commit_date` DATETIME NULL,
  `ancestor_date` DATETIME NULL,
  `parent1_date` DATETIME NULL,
  `parent2_date` DATETIME NULL,
  `pull_request` INT NULL,
  `Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Repository_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `merge_commit_hash_UNIQUE` (`merge_commit_hash` ASC),
  INDEX `fk_Merge_Scenario_Repository_Information1_idx` (`Repository_id` ASC),
  CONSTRAINT `fk_Merge_Scenario_Repository_Information1`
    FOREIGN KEY (`Repository_id`)
    REFERENCES `Merge_Data`.`Repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Merge_Replay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Merge_Replay` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Merge_Replay` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `merge_technique` VARCHAR(15) NULL,
  `is_conflict` INT NULL,
  `can_compile` INT NULL,
  `can_pass_test` INT NULL,
  `execution_time` FLOAT NULL,
  `result_is_equal_to_replay` INT NULL,
  `Merge_Scenario_id` INT NOT NULL,
  `Merge_Scenario_Repository_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `Merge_Scenario_id`, `Merge_Scenario_Repository_id`),
  INDEX `fk_Merge_Replay_Merge_Scenario1_idx` (`Merge_Scenario_id` ASC, `Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_Merge_Replay_Merge_Scenario1`
    FOREIGN KEY (`Merge_Scenario_id`)
    REFERENCES `Merge_Data`.`Merge_Scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Conflicting_File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Conflicting_File` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Conflicting_File` (
  `id` INT NOT NULL,
  `file_path_name` VARCHAR(1000) NULL,
  `conflict_type` VARCHAR(40) NULL DEFAULT 0,
  `Merge_Replay_id` INT NOT NULL,
  `Merge_Replay_Merge_Scenario_id` INT NOT NULL,
  `Merge_Replay_Merge_Scenario_Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Merge_Replay_id`, `Merge_Replay_Merge_Scenario_id`, `Merge_Replay_Merge_Scenario_Repository_id`),
  INDEX `fk_Conflicting_File_Merge_Replay1_idx` (`Merge_Replay_id` ASC, `Merge_Replay_Merge_Scenario_id` ASC, `Merge_Replay_Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_Conflicting_File_Merge_Replay1`
    FOREIGN KEY (`Merge_Replay_id` , `Merge_Replay_Merge_Scenario_id` , `Merge_Replay_Merge_Scenario_Repository_id`)
    REFERENCES `Merge_Data`.`Merge_Replay` (`id` , `Merge_Scenario_id` , `Merge_Scenario_Repository_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Merge_Related_commit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Merge_Related_commit` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Merge_Related_commit` (
  `id` INT NOT NULL,
  `commit_hash` CHAR(40) NULL,
  `date` DATETIME NULL,
  `message` VARCHAR(400) NULL,
  `branch` VARCHAR(45) NULL,
  `merge_commit_parent` INT NULL DEFAULT '',
  `file_added_num` INT NULL,
  `file_removed_num` INT NULL,
  `file_renamed_num` INT NULL,
  `file_copied_num` INT NULL,
  `file_modified_num` INT NULL,
  `line_added_num` INT NULL,
  `line_removed_num` INT NULL,
  `Merge_Scenario_id` INT NOT NULL,
  `Merge_Scenario_Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Merge_Scenario_id`, `Merge_Scenario_Repository_id`),
  INDEX `fk_Commit_Merge_Scenario1_idx` (`Merge_Scenario_id` ASC, `Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_Commit_Merge_Scenario1`
    FOREIGN KEY (`Merge_Scenario_id`)
    REFERENCES `Merge_Data`.`Merge_Scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Code_Complexity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Code_Complexity` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Code_Complexity` (
  `id` INT NOT NULL,
  `merge_commitcommit_hash` CHAR(40) NULL,
  `measure1_diff` INT NULL,
  `Merge_Scenario_id` INT NOT NULL,
  `Merge_Scenario_Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Merge_Scenario_id`, `Merge_Scenario_Repository_id`),
  INDEX `fk_Code_Complexity_Merge_Scenario1_idx` (`Merge_Scenario_id` ASC, `Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_Code_Complexity_Merge_Scenario1`
    FOREIGN KEY (`Merge_Scenario_id`)
    REFERENCES `Merge_Data`.`Merge_Scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Conflicting_Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Conflicting_Region` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Conflicting_Region` (
  `id` INT NOT NULL,
  `parent1_path` VARCHAR(1000) NULL,
  `parent2_path` VARCHAR(1000) NULL,
  `parent1_start_line` INT NULL,
  `parent1_length` INT NULL,
  `parent2_start_line` INT NULL,
  `parent2_length` INT NULL,
  `Conflicting_File_Merge_Replay_id` INT NOT NULL,
  `Conflicting_File_Merge_Replay_Merge_Scenario_id` INT NOT NULL,
  `Conflicting_File_Merge_Replay_Merge_Scenario_Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Conflicting_File_Merge_Replay_id`, `Conflicting_File_Merge_Replay_Merge_Scenario_id`, `Conflicting_File_Merge_Replay_Merge_Scenario_Repository_id`),
  INDEX `fk_Conflicting_region_Conflicting_File1_idx` (`Conflicting_File_Merge_Replay_id` ASC, `Conflicting_File_Merge_Replay_Merge_Scenario_id` ASC, `Conflicting_File_Merge_Replay_Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_Conflicting_region_Conflicting_File1`
    FOREIGN KEY (`Conflicting_File_Merge_Replay_id` , `Conflicting_File_Merge_Replay_Merge_Scenario_id` , `Conflicting_File_Merge_Replay_Merge_Scenario_Repository_id`)
    REFERENCES `Merge_Data`.`Conflicting_File` (`Merge_Replay_id` , `Merge_Replay_Merge_Scenario_id` , `Merge_Replay_Merge_Scenario_Repository_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merge_Data`.`Code_Style_Violation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merge_Data`.`Code_Style_Violation` ;

CREATE TABLE IF NOT EXISTS `Merge_Data`.`Code_Style_Violation` (
  `id` INT NOT NULL,
  `merge_commit_style_violation_num` INT NULL,
  `ancestor_style_violation_num` INT NULL,
  `parent1_style_violation_num` INT NULL,
  `parent2_style_violation_num` INT NULL,
  `Merge_Scenario_id` INT NOT NULL,
  `Merge_Scenario_Repository_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Merge_Scenario_id`, `Merge_Scenario_Repository_id`),
  INDEX `fk_code_violation_Merge_Scenario1_idx` (`Merge_Scenario_id` ASC, `Merge_Scenario_Repository_id` ASC),
  CONSTRAINT `fk_code_violation_Merge_Scenario1`
    FOREIGN KEY (`Merge_Scenario_id`)
    REFERENCES `Merge_Data`.`Merge_Scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
